version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:8181
    volumes:
    - ./wordpress:/var/www/html
    - ./ngnix/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USR: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: seret
  php:
    build:
      context: 
        dockerfile: php.dockerfile
    Volumes:
    - ./wordpress:/var/www/html
